# 左臂
# 左臂空闲放置点
LeftArmIdle:
  angles: [48.48, 26.74, -87.2, -65.34, 46.81, -26.15]

# 左臂食物框识别位点
LeftArmContainerRec:
  angles: [48.48, 26.74, -87.2, -65.34, 46.81, -26.15]

# 左臂零食识别位点
LeftArmSnackRec:
  angles: [-66.27, 5.44, -148.83, 123.8, 72.58, 24.6]

# 左臂零食放置位点
LeftArmSnackPlacement:
  # x y 待定,z 确定 
  coords:  [0, 0, 0, -180, 0.0, -90]

# 左臂零食框递送时的位点
LeftArmContainerDelivery:
# TODO待测
  angles: [0, 0, 0, 0, 0, 0]

# 左臂零食框放置时的位点
LeftArmContainerPlacement:
# TODO待测
  angles: [0, 0, 0, 0, 0, 0]

# 右臂
# 右臂空闲放置点
RightArmIdle:
  angles: [-48.48, 26.74, -87.21, 65.36, 46.82, 26.16]

# 右臂食物框识别位点
RightArmContainerRec:
  angles: [-48.48, 26.74, -87.21, 65.36, 46.82, 26.16]

# 右臂零食识别位点
RightArmSnackRec:
  angles: [66.27, 5.44, -148.83, -123.8, 72.58, -24.6]

# 右臂零食放置位点
RightArmSnackPlacement:
# xyz不确定
  coords:  [-999, -999, -999, -180, 0.0, 90]

# 右臂零食框递送时的位点
RightArmContainerDelivery:
# TODO待测
  angles: [0, 0, 0, 0, 0, 0]

# 右臂零食框放置时的位点
RightArmContainerPlacement:
# TODO待测
  coords:  [0, 0, 0, 0, 0, 0]


# 杯子抓取位点
CupGrab:
  # xyz不确定
  coords:  [-999, -999, 210, 90, 0, 90]

# 杯子识别位点
CupRec:
  angles: [-138.4, 22.23, -154.04, 43.12, 57.25, 2.93]

# 杯子接水位点     
CupWater:
  # xyz不确定
  coords:  [-999, -999, -999, 90, 0, 90]
  
# 杯子转移位点
# TODO:待测
CupDelivery:
  angles: [0, 0, 0, 0, 0, 0]

# 杯子的放置位姿
CupPlacement:
  # TODO: 待测
  angles: [0, 0, 0, 0, 0, 0]

# 咖啡机识别位点
CoffeeMachineRec:
  angles: [-71.36, -7.87, -155.8, 121.34, 73.92, 31.57]

# 咖啡机开启的位点
CoffeeMachineOpenPrepare:
  # x y z 都不确定, 手势确定
  coords:  [-999, -999, -999, 121.34, 73.92, 31.57]

# 咖啡机关闭的位点
CoffeeMachineClosePrepare:
  # x y z 都不确定, 手势确定
  coords:  [-999, -999, -999, 121.34, 73.92, 31.57]

# 零食抓取位点
SnackGrap:
  # x,y,z待定
  coords:  [0, 0, 0, -90, 0.0, -90]

