# 左臂
# 左臂空闲放置点
LeftArmIdle:
  angles: [-71.22, 62.77, -35.52, 66.98, 20.46, 35.6]

# 左臂食物框识别位点
LeftArmContainerRec:
  coords: [330, 205, 435, -180, 0, -90]

# 左臂零食识别位点
LeftArmSnackRec:
  angles: [-118.03, -9.44, -149.65, 90.54, 49.85, 47.64]

# ! 新增
# 左臂抓零食位点准备位点(识别位置前往下层会碰撞)
LeftArmGripSnackPre:
  coords:  [240, 200, 370, -90, 0, -90]

# 左臂抓零食位点
LeftArmGripSnack:
  # x y z待定(与识别框的偏移量), 手势确定
  coords:  [-999, -999, -999, -90, 0, -90]

# 左臂零食放置位点 准备点
LeftArmSnackPlacementPre:
  coords:  [230, 270, 330, -90, 0, -90]

# 左臂零食放置位点
LeftArmSnackPlacement:
  # x y 待定(与识别框的偏移量), z比抓取框高20mm 
  coords:  [-999, -999, 290, -180, 0, -90]

# 左臂抓框时, 躲避放置零食的位点
LeftArmGripContainerDodge:
  # x y 与 左臂抓框时的位点 相同, z轴比抓框高 
  coords:  [-1, -1, 290, -180, 0.0, -90]

# 左臂抓框时的准备位点
LeftArmGripContainerPre:
  # x y 与 左臂抓框时的位点 相同, z轴比抓框高40mm  
  coords:  [-999, -999, 255, -180, 0.0, -90]

# 左臂抓框时的位点
LeftArmGripContainer:
  # x y 待定(与识别框的偏移量)
  coords:  [0, 0, -30, 0, 0, 0]

# 左臂零食框递送时的位点
LeftArmContainerDelivery:
# x轴 比抓框时多50mm, y轴 与抓取框时相同, z轴 比抓取框高20mm, 
  coords: [0, 0, 100, 0, 0, 0]

# 左臂零食框放置时的位点
LeftArmContainerPlacement:
# x轴递送时相同 , y轴 与转移框时相同, z比抓取框高10mm, 
  coords: [0, 0, -100, 0, 0, 0]

# 左臂咖啡机识别位点 开机位点
LeftArmMachineTurnOnRec:
  coords: [160, 100, 330, -90, 0, -90]

# TODO:不需要识别
# 左臂咖啡机识别位点, 关机位点, 需要修改
LeftArmMachineTurnOFFRec:
  angles: [-78.94, 14.88, -126.71, 117.4, 73.22, 39.54]

# 左臂咖啡机开启的位点
LeftArmMachineTurnOnPre:
  # x y z 都不确定, 手势确定
  coords:  [-999, -999, -999, -90, 0.0, -90]

# 左臂咖啡机开启时向上拨一拨
LeftArmMachineTurnOnClick:
  # x y z 都不确定, 手势确定
  coords:  [0, 0, 20, 0, 0, 0]

# 左臂咖啡机转移位点
LeftArmMachineTransfrom:
  # x y z 都不确定, 手势确定
  coords:  [-999, -999, -999, -90, 0.0, -90]

# 左臂咖啡机关闭的位点
LeftArmMachineTurnOffPre:
  # x y z 都不确定, 手势确定
  coords:  [-999, -999, -999, -90, 0.0, -90]

# 左臂咖啡机关闭时向下拨一拨
LeftArmMachineTurnOffClick:
  coords:  [0, 0, -25, 0, 0, 0]


# !TODO:右臂
# 右臂空闲放置点
RightArmIdle:
  angles: [71.22, 62.77, -35.52, -66.98, 20.46, -35.6]

# 右臂食物框识别位点
RightArmContainerRec:
  coords: [330, -100, 435, -180, 0.0, 90]

# 右臂零食识别位点
RightArmSnackRec:
  angles: [101.79, 13.49, -152.23, -86.73, 58.11, -16.5]

# 右臂抓零食位点准备位点
RightArmGripSnackPre:
  coords:  [240, -140, 360, 90, 0, 90]

# 右臂抓零食位点
RightArmGripSnack:
  # x y z待定(与识别框的偏移量), 手势确定
  coords:  [-999, -999, -999, 90, 0, 90]

# 右臂零食放置位点 准备点
RightArmSnackPlacementPre:
  coords:  [230, -220, 330, 90, 0, 90]

# 右臂零食放置位点
RightArmSnackPlacement:
  # x y 待定(与识别框的偏移量), z比抓取框高20mm 
  coords:  [-999, -999, 290, -180, 0, 90]


# 右臂抓框时, 躲避放置零食的位点
RightArmGripContainerDodge:
  # x y 与 左臂抓框时的位点 相同, z轴比抓框高 
  coords:  [-1, -1, 290, -180, 0, 90]


# 右臂抓框时的准备位点
RightArmGripContainerPre:
  # x y 与 左臂抓框时的位点 相同, z轴比抓框高 
  coords:  [-1, -1, 260, -180, 0, 90]

# 右臂抓框时的位点
RightArmGripContainer:
  coords:  [0, 0, -30, 0, 0, 0]

# 右臂零食框递送时的位点
RightArmContainerDelivery:
# x轴 比抓框时多50mm, y 与抓取框时相同, z比抓取框高20mm, x轴写死

  coords: [0, 0, 100, 0, 0, 0]

# 右臂零食框放置时的位点
RightArmContainerPlacement:
# x轴递送时相同 y 与抓取框时相同,  z比抓取框高10mm
  coords: [0, 0, -100, 0, 0, 0]

# 右臂识别杯子准备动作
RightArmCupRecPre:
  # angles: [0,0,-90,0,90,0]
  angles: [0,0,-115,0,90,0]

# 右臂杯子识别位点
RightArmCupRec:
  angles: [-147.43, 15.12, -137.21, 48.36, 38.58, 23.61]

# 右臂杯子抓取位点 准备
RightArmCupGrabPre:
  # x, z确定,y轴与抓取位相同
  coords:  [200, -1, 90, 90, 0, 90]

# 右臂杯子抓取位点
RightArmCupGrab:
  # xy不确定, z确定
  coords:  [-999, -999, 90, 90, 0, 90]

# 右臂杯子接水位点     
RightArmCupWater:
  # xy不确定, z确定
  coords:  [-999, -999, 140, 90, 0, 90]
  
# 右臂杯子转移位点
RightArmCupDelivery:
  coords: [290, 0, 140, 90, 0, 90]

# 右臂杯子的放置位姿
RightArmCupPlacement:
  coords: [0, 0, -40, 0, 0, 0]