# 左臂
# 左臂空闲放置点
LeftArmIdle:
  angles: [-48.48, 26.74, -87.21, 65.36, 46.82, 26.16]

# 左臂食物框识别位点
LeftArmContainerRec:
  angles: [-48.48, 26.74, -87.21, 65.36, 46.82, 26.16]

# 左臂零食识别位点
LeftArmSnackRec:
  angles: [-66.27, 5.44, -148.83, 123.8, 72.58, 24.6]

# 左臂抓零食位点
LeftArmGripSnack:
  # x y z待定(与识别框的偏移量), 手势确定
  coords:  [-999, -999, -999, -90, 0.0, -90]

# 左臂零食放置位点 准备点
LeftArmSnackPlacementPre:
# TODO: 待定
  # x y 待定(与识别框的偏移量), z比抓取框高20mm 
  coords:  [-999, -999, 380, -180, 0.0, -90]

# 左臂零食放置位点
LeftArmSnackPlacement:
  # x y 待定(与识别框的偏移量), z比抓取框高20mm 
  coords:  [-999, -999, 380, -180, 0.0, -90]

# 左臂抓框时的准备位点
LeftArmGripContainerPre:
  # x y 与 左臂抓框时的位点 相同, z轴比抓框高40mm  
  coords:  [-999, -999, 400, -180, 0.0, -90]

# 左臂抓框时的位点
LeftArmGripContainer:
  # x y 待定(与识别框的偏移量)
  # coords:  [-999, -999, 360, -180, 0.0, -90]
  coords:  [0, 0, -40, 0, 0, 0]

# 左臂零食框递送时的位点
LeftArmContainerDelivery:
# x轴 比抓框时多50mm, y轴 与抓取框时相同, z轴 比抓取框高20mm, 
  # coords:  [-1, -1, 380, -180, 0.0, -90]
  coords: [0, 0, 20, 0, 0, 0]

# 左臂零食框放置时的位点
LeftArmContainerPlacement:
# x轴递送时相同 , y轴 与转移框时相同, z比抓取框高10mm, 
  # coords:  [-1, -1, 370, -180, 0.0, -90]
  coords: [0, 0, -20, 0, 0, 0]

# 左臂咖啡机识别位点
LeftArmMachineTurnOnRec:
  angles: [-71.36, -7.87, -155.8, 121.34, 73.92, 31.57]

# 左臂咖啡机识别位点, 关机位点, 需要修改
LeftArmMachineTurnOFFRec:
  angles: [-78.94, 14.88, -126.71, 117.4, 73.22, 39.54]

# 左臂咖啡机开启的位点
LeftArmMachineTurnOnPre:
  # x y z 都不确定, 手势确定
  coords:  [-999, -999, -999, -90, 0.0, -90]

# 左臂咖啡机关闭的位点
LeftArmMachineTurnOffPre:
  # x y z 都不确定, 手势确定
  coords:  [-999, -999, -999, -90, 0.0, -90]

# !TODO:右臂
# 右臂空闲放置点
RightArmIdle:
  angles: [48.48, 26.74, -87.21, -65.36, 46.82, -26.16]

# 右臂食物框识别位点
RightArmContainerRec:
  angles: [48.48, 26.74, -87.21, -65.36, 46.82, -26.16]

# 右臂零食识别位点
RightArmSnackRec:
  angles: [66.27, 5.44, -148.83, -123.8, 72.58, -24.6]

# 右臂抓零食位点
RightArmGripSnack:
  # x y z待定(与识别框的偏移量), 手势确定
  coords:  [-999, -999, -999, 90, 0, 90]

# 右臂零食放置位点 准备点
LeftArmSnackPlacementPre:
# TODO: 待定
  # x y 待定(与识别框的偏移量), z比抓取框高20mm 
  coords:  [-999, -999, 380, -180, 0.0, -90]


# 右臂零食放置位点
RightArmSnackPlacement:
  # x y 待定(与识别框的偏移量), z比抓取框高20mm 
  coords:  [-999, -999, 380, -180, 0, 90]

# 右臂抓框时的准备位点
RightArmGripContainerPre:
  # x y 与 左臂抓框时的位点 相同, z轴比抓框高40mm 
  coords:  [-1, -1, 400, -180, 0.0, 90]

# 右臂抓框时的位点
RightArmGripContainer:
  # x y 待定(与识别框的偏移量)
  # coords:  [-999, -999, 360, -180, 0.0, 90]
  coords:  [0, 0, -40, 0, 0, 0]

# 右臂零食框递送时的位点
RightArmContainerDelivery:
# x轴 比抓框时多50mm, y 与抓取框时相同, z比抓取框高20mm, x轴写死
  # coords: [-1, -1, 380, -180, 0, 90]
  coords: [0, 0, 20, 0, 0, 0]

# 右臂零食框放置时的位点
RightArmContainerPlacement:
# x轴递送时相同 y 与抓取框时相同,  z比抓取框高10mm
  # coords: [-1, -1, 370, -180, 0, 90]
  coords: [0, 0, -20, 0, 0, 0]

# 右臂识别杯子准备动作
RightArmCupRecPre:
  # angles: [0,0,-90,0,90,0]
  angles: [0,0,-115,0,90,0]

# 右臂杯子识别位点
RightArmCupRec:
  angles: [-135.79, 22.83, -152.09, 46.44, 56.43, 4.23]

# 右臂杯子抓取位点 准备
RightArmCupGrabPre:
  # x, z确定,y轴与抓取位相同
  coords:  [250, -1, 220, 90, 0, 90]

# 右臂杯子抓取位点
RightArmCupGrab:
  # xy不确定, z确定
  coords:  [-999, -999, 220, 90, 0, 90]

# 右臂杯子接水位点     
RightArmCupWater:
  # xy不确定, z确定
  coords:  [-999, -999, -999, 90, 0, 90]
  
# 右臂杯子转移位点
RightArmCupDelivery:
  coords: [300, 0, 240, 90, 0, 90]

# 右臂杯子的放置位姿
RightArmCupPlacement:
  # 同杯子转移位点
  # coords: [300, 0, 220, 90, 0, 90]
  coords: [0, 0, -20, 0, 0, 0]