# 左臂
# 左臂空闲放置点
LeftArmIdle:
  angles: [-71.31, 63.55, -34.37, 67.69, 20.23, 36.37]

# 左臂食物框识别位点
LeftArmContainerRec:
  angles: [-57.8, 32.65, -66.77, 75.38, 33.39, 42.65]

# 左臂零食识别位点
LeftArmSnackRec:
  angles: [-108.42, -20.47, -140.94, 109.56, 60.68, 69.66]

# 左臂抓零食位点
LeftArmGripSnack:
  # x y z待定(与识别框的偏移量), 手势确定
  coords:  [-999, -999, -999, -90, 0, -90]

# TODO:待修改
# 左臂零食放置位点 准备点
LeftArmSnackPlacementPre:
  # coords:  [230, 170 , 450, -180, 0, 0]
  coords:  [230, 170 , 500, -90, 0, -90]

# TODO:待修改
# 左臂零食放置位点
LeftArmSnackPlacement:
  # x y 待定(与识别框的偏移量), z比抓取框高20mm 
  coords:  [-999, -999, 400, -180, 0, -90]

# 左臂抓框时的准备位点
LeftArmGripContainerPre:
  # x y 与 左臂抓框时的位点 相同, z轴比抓框高40mm  
  coords:  [-999, -999, 430, -180, 0.0, -90]

# 左臂抓框时的位点
LeftArmGripContainer:
  # x y 待定(与识别框的偏移量)
  # coords:  [-999, -999, 360, -180, 0.0, -90]
  coords:  [0, 0, -60, 0, 0, 0]

# 左臂零食框递送时的位点
LeftArmContainerDelivery:
# x轴 比抓框时多50mm, y轴 与抓取框时相同, z轴 比抓取框高20mm, 
  # coords:  [-1, -1, 380, -180, 0.0, -90]
  coords: [0, 0, 80, 0, 0, 0]

# 左臂零食框放置时的位点
LeftArmContainerPlacement:
# x轴递送时相同 , y轴 与转移框时相同, z比抓取框高10mm, 
  # coords:  [-1, -1, 370, -180, 0.0, -90]
  coords: [0, 0, -80, 0, 0, 0]

# 左臂咖啡机识别位点
LeftArmMachineTurnOnRec:
  angles: [-71.36, -7.87, -155.8, 121.34, 73.92, 31.57]

# 左臂咖啡机识别位点, 关机位点, 需要修改
LeftArmMachineTurnOFFRec:
  angles: [-78.94, 14.88, -126.71, 117.4, 73.22, 39.54]

# 左臂咖啡机开启的位点
LeftArmMachineTurnOnPre:
  # x y z 都不确定, 手势确定
  coords:  [-999, -999, -999, -90, 0.0, -90]

# 左臂咖啡机开启时向上拨一拨
LeftArmMachineTurnOnClick:
  # x y z 都不确定, 手势确定
  coords:  [0, 0, 20, 0, 0, 0]


# 左臂咖啡机关闭的位点
LeftArmMachineTurnOffPre:
  # x y z 都不确定, 手势确定
  coords:  [-999, -999, -999, -90, 0.0, -90]


# 左臂咖啡机关闭时向下拨一拨
LeftArmMachineTurnOffClick:
  coords:  [0, 0, -20, 0, 0, 0]


# !TODO:右臂
# 右臂空闲放置点
RightArmIdle:
  angles: [71.31, 63.55, -34.38, -67.73, 20.23, -36.42]

# 右臂食物框识别位点
RightArmContainerRec:
  angles: [52.75, 42.33, -66.09, -67.39, 40.94, -31.12]

# 右臂零食识别位点
RightArmSnackRec:
  angles: [76.87, 21.81, -150.56, -107.2, 61.99, -8.4]

# 右臂抓零食位点
RightArmGripSnack:
  # x y z待定(与识别框的偏移量), 手势确定
  coords:  [-999, -999, -999, 90, 0, 90]

# TODO:待修改
# 右臂零食放置位点 准备点
RightArmSnackPlacementPre:
  coords:  [230, -170, 500,  90, 0, 90]

# TODO:待修改
# 右臂零食放置位点
RightArmSnackPlacement:
  # x y 待定(与识别框的偏移量), z比抓取框高20mm 
  coords:  [-999, -999, 400, -180, 0, 90]

# 右臂抓框时的准备位点
RightArmGripContainerPre:
  # x y 与 左臂抓框时的位点 相同, z轴比抓框高40mm 
  coords:  [-1, -1, 430, -180, 0.0, 90]

# 右臂抓框时的位点
RightArmGripContainer:
  # x y 待定(与识别框的偏移量)
  # coords:  [-999, -999, 360, -180, 0.0, 90]
  coords:  [0, 0, -60, 0, 0, 0]

# 右臂零食框递送时的位点
RightArmContainerDelivery:
# x轴 比抓框时多50mm, y 与抓取框时相同, z比抓取框高20mm, x轴写死
  # coords: [-1, -1, 380, -180, 0, 90]
  coords: [0, 0, 80, 0, 0, 0]

# 右臂零食框放置时的位点
RightArmContainerPlacement:
# x轴递送时相同 y 与抓取框时相同,  z比抓取框高10mm
  # coords: [-1, -1, 370, -180, 0, 90]
  coords: [0, 0, -80, 0, 0, 0]

# 右臂识别杯子准备动作
RightArmCupRecPre:
  # angles: [0,0,-90,0,90,0]
  angles: [0,0,-115,0,90,0]

# 右臂杯子识别位点
RightArmCupRec:
  angles: [-141.77, 25.64, -142.14, 43.76, 50.75, 9.71]

# 右臂杯子抓取位点 准备
RightArmCupGrabPre:
  # x, z确定,y轴与抓取位相同
  coords:  [250, -1, 220, 90, 0, 90]

# 右臂杯子抓取位点
RightArmCupGrab:
  # xy不确定, z确定
  coords:  [-999, -999, 220, 90, 0, 90]

# 右臂杯子接水位点     
RightArmCupWater:
  # xy不确定, z确定
  coords:  [-999, -999, -999, 90, 0, 90]
  
# 右臂杯子转移位点
RightArmCupDelivery:
  coords: [300, 0, 240, 90, 0, 90]

# 右臂杯子的放置位姿
RightArmCupPlacement:
  # 同杯子转移位点
  # coords: [300, 0, 220, 90, 0, 90]
  coords: [0, 0, -20, 0, 0, 0]