# 左臂
# 左臂空闲放置点
LeftArmIdle:
  angles: [0, 0, 0, 0, 0, 0]


# 左臂食物框识别位点
LeftArmContainerRec:
  angles: [0, 0, 0, 0, 0, 0]

# 左臂零食识别位点
LeftArmSnackRec:
  angles: [0, 0, 0, 0, 0, 0]

# 左臂零食放置位点
LeftArmSnackPlacement:
  angles: [0, 0, 0, 0, 0, 0]

# 左臂零食框递送时的位点
LeftArmContainerDelivery:
  angles: [0, 0, 0, 0, 0, 0]

# 左臂零食框放置时的位点
LeftArmContainerPlacement:
  angles: [0, 0, 0, 0, 0, 0]

# 右臂
# 右臂空闲放置点
RightArmIdle:
  angles: [0, 0, 0, 0, 0, 0]

# 右臂食物框识别位点
RightArmContainerRec:
  angles: [0, 0, 0, 0, 0, 0]

# 右臂零食识别位点
RightArmSnackRec:
  angles: [0, 0, 0, 0, 0, 0]

# 右臂零食放置位点
RightArmSnackPlacement:
  x:  11.80      # 半确定, 根据架子距离, 桌角深度给出
  y:  20.819     # 不确定, 需要识别给出
  z:  0          # 不确定, 需要识别给出
  rx: 0 
  ry: 0 
  rz: 0
  coords:  [0, 0, 0, 0, 0, 0]

# 右臂零食框递送时的位点
RightArmContainerDelivery:
  angles: [0, 0, 0, 0, 0, 0]

# 右臂零食框放置时的位点
RightArmContainerPlacement:
  x:  11.80      # 半确定, 根据架子距离, 桌角深度给出
  y:  20.819     # 不确定, 需要识别给出
  z:  0          # 不确定, 需要识别给出
  rx: 0 
  ry: 0 
  rz: 0
  coords:  [0, 0, 0, 0, 0, 0]

# 共用
# 杯子抓取位点
CupGrab:
  x:  11.80
  y:  20.819      # 不确定, 需要识别给出
  z:  0           # 半确定, 根据桌子高度, 机械臂原点高度给出
  rx: 0 
  ry: 0 
  rz: 0
  coords:  [0, 0, 0, 0, 0, 0]

# 杯子识别位点
CupRec:
  angles: [0, 0, 0, 0, 0, 0]

# 杯子接水位点     
CupWater:
  coords:  [0, 0, 0, 0, 0, 0]
  
# 杯子转移位点
CupDelivery:
  angles: [0, 0, 0, 0, 0, 0]

# 杯子的放置位姿
CupPlacement:
  angles: [0, 0, 0, 0, 0, 0]

# 咖啡机识别位点
CoffeeMachineRec:
  angles: [0, 0, 0, 0, 0, 0]

# 咖啡机按下的位点
CoffeeMachineClick:
  x:  11.80       # 不确定, 需要识别给出
  y:  20.819      # 不确定, 需要识别给出
  z:  0           # 半确定, 根据桌子高度, 咖啡机高度, 机械臂原点高度给出
  rx: 0 
  ry: 0 
  rz: 0
  coords:  [0, 0, 0, 0, 0, 0]

# 零食抓取位点
SnackGrap:
  x:  11.80      # 半确定, 根据架子距离, 桌角深度给出
  y:  20.819     # 不确定, 需要识别给出
  z:  0          # 不确定, 需要识别给出
  rx: 0 
  ry: 0 
  rz: 0
  coords:  [0, 0, 0, 0, 0, 0]

