# 左臂抓零食
LeftArmGripSnack:
  x_bias: -100
  y_bias: -58
  z_bias: +45

# 左臂上层零食放置高度
LeftArmTopSnackPlacement:
  z_const: 550

# 左臂下层零食放置高度
LeftArmBottomSnackPlacement:
  z_const: 380

# 左臂抓容器
LeftArmGripContainer:
  x_bias : -36
  y_bias : 45
  z_const: 390     # 这里的z无用

# 左臂松零食(相对于抓容器的位置)
LeftArmLossenSnack:
  x_bias: +10
  y_bias: -60
  z_bias: 20  # 410

# TODO:待定
# 左臂抓容器前, 躲避放置零食的位点(相对于抓容器的位置)
LeftArmGripContainerDodge:
  x_bias : 0
  y_bias : 70 
  z_const: 390     # 这里的z无用

# 左臂准备 开 咖啡开关
LeftArmGripTurnOnMachineSwitch:
  x_bias: -164
  y_bias: -30
  z_bias: -40     

# 左臂从开咖啡机转移到关咖啡机(相对开咖啡机偏移)
LeftArmGripTurnOFFMachineSwitch:
  x_bias: -30
  y_bias: -20
  z_bias: 160          

# 左臂准备 关 咖啡开关(相对开咖啡机偏移)
LeftArmGripTurnOFFMachineSwitch:
  x_bias: 10
  y_bias: -20
  z_bias: 160 

# 左臂识别开关换算到接水点位置
# TODO:
LeftArmWaterCup:
  x_bias: -205
  y_bias: -98
  z_const: 230


# !!!!!以下为右臂

# 右臂抓零食
RightArmGripSnack:
  x_bias: 90
  y_bias: 58
  z_bias: 20

# 右臂上层零食放置高度
RightArmTopSnackPlacement:
  z_const: 550

# 右臂下层零食放置高度
RightArmBottomSnackPlacement:
  z_const: 400

# 右臂抓容器
RightArmGripContainer:     # 这里的z无用
  x_bias : 40
  y_bias : 50
  z_const: 390   # 有用的嘛

# 右臂松零食(相对于抓容器的位置)
RightArmLossenSnack:
  x_bias: 30
  y_bias: 80
  z_bias: 20  # 410


# TODO:待定
# 右臂抓容器, 躲避放置零食的位点(相对于抓容器的位置)
RighttArmGripContainerDodge:
  x_bias : 0
  y_bias : -70
  z_const: 360        # 这里的z无用

# 右臂抓杯子
RightArmGripCup:
  x_bias : -90
  y_bias : 83
  z_const: 220

# 右臂杯子接水
RightArmWaterCup:
  x_bias : -205
  y_bias : 98
  z_const: 240



