# 左臂抓零食
LeftArmGripSnack:
  x_bias: -110
  y_bias: -78
  z_bias: +20

# 左臂抓零食DNN(深度神经网络识别)
LeftArmGripSnackDNN:
  x_bias: -70
  y_bias: -78
  z_bias: +20


# 左臂上层零食放置高度
LeftArmTopSnackGrip:
  # z_const: 465
  z_const: 430

# 左臂下层零食放置高度
LeftArmBottomSnackGrip:
  z_const: 280

# 左臂抓容器
LeftArmGripContainer:
  x_bias : -66
  y_bias : -50
  z_const: 240     # 这里的z无用

# 左臂松零食(相对于抓容器的位置)
LeftArmLossenSnack:
  x_bias: +30
  y_bias: -90
  z_bias: 20      # 这里的z无用

# 左臂抓容器前, 躲避放置零食的位点(相对于抓容器的位置)
LeftArmGripContainerDodge:
  x_bias : 0
  y_bias : 80 
  z_const: 390     # 这里的z无用

# 左臂准备 开 咖啡开关
LeftArmGripTurnOnMachineSwitch:
  x_bias: -165
  y_bias: -40
  z_bias: -60     

# 左臂从开咖啡机 转移 到关咖啡机(相对开咖啡机偏移)
LeftArmGripTranMachineSwitch:
  x_bias: -30
  y_bias: -20
  z_bias: 160          

# 左臂准备 关 咖啡开关(相对开咖啡机偏移)
LeftArmGripTurnOFFMachineSwitch:
  x_bias: 10
  y_bias: -20
  z_bias: 160 


# 左臂识别开关换算到接水点位置
# y轴无偏差估计
LeftArmWaterCup:
  x_bias: -25
  y_bias: -35
  z_const: 130     # 有用


# !!!!!以下为右臂

# 右臂抓零食
RightArmGripSnack:
  x_bias: -80
  y_bias: 58
  z_bias: 20

# 右臂抓零食(深度神经网络识别)
RightArmGripSnackDNN:
  x_bias: -70
  y_bias: 68
  z_bias: 20

# 右臂上层零食放置高度
RightArmTopSnackGrip:
  # z_const: 450
  z_const: 430

# 右臂下层零食放置高度
RightArmBottomSnackGrip:
  z_const: 280

# 右臂抓容器
RightArmGripContainer:     
  x_bias : 20
  y_bias : 50
  z_const: 390   # 这里的z无用

# 右臂松零食(相对于抓容器的位置)
RightArmLossenSnack:
  x_bias: -50
  y_bias: 80
  z_bias: 20    # 这里的z无用


# 右臂抓容器, 躲避放置零食的位点(相对于抓容器的位置)
RightArmGripContainerDodge:
  x_bias : 0
  y_bias : -70
  z_const: 360        # 这里的z无用

# 右臂抓杯子
RightArmGripCup:
  x_bias : -90
  y_bias : 83
  z_const: 90    # 有用

# 右臂杯子接水
RightArmWaterCup:
  x_bias : -205
  y_bias : 98
  z_const: 240



