# 左臂抓零食
LeftArmGripSnack:
  x_bias: -90
  y_bias: -78
  z_bias: 20

# 左臂松零食
# 相对于抓容器的位置
LeftArmLossenSnack:
  x_bias: 0
  y_bias: -40
  z_bias: 20  # 380

# 左臂抓容器
LeftArmGripContainer:
  x_bias : -20
  y_bias : -27
  z_const: 360

# 左臂准备 开 咖啡开关
LeftArmGripTurnOnMachineSwitch:
  x_bias: -160
  y_bias: -78
  z_bias: 20               #原为20

# 左臂准备 关 咖啡开关
# TODO:待定
LeftArmGripTurnOFFMachineSwitch:
  x_bias: -160
  y_bias: -78
  z_bias: 20  

# !!!!!以下为右臂

# 右臂抓零食
RightArmGripSnack:
  # x_bias: -90
  x_bias: -100
  y_bias: 78
  z_bias: -5

# 右臂松零食
# 相对于抓容器的位置
RightArmLossenSnack:
  x_bias: 0
  y_bias: 40
  z_bias: 20  # 380

# 右臂抓容器
RightArmGripContainer:
  x_bias : -10
  y_bias : 44
  z_const: 360


# 右臂抓杯子
RightArmGripCup:
  x_bias : -90
  y_bias : 78
  z_const: 220

# 右臂杯子倒水
RightArmWaterCup:
  # x_bias : -195
  x_bias : -205
  y_bias : 98
  z_const: 230