# 左臂抓零食
LeftArmGripSnack:
  x_bias: -90
  y_bias: -78
  z_bias: 20

# 左臂松零食
# 相对于抓容器的位置
LeftArmLossenSnack:
  x_bias: -50
  y_bias: -50
  z_bias: 20  # 380

# 左臂抓容器
LeftArmGripContainer:
  x_bias : 50
  y_bias : 112
  z_const: 360

# 左臂准备 开 咖啡开关
LeftArmGripTurnOnMachineSwitch:
  x_bias: -160
  y_bias: -78
  z_bias: 20               #原为20

# 左臂准备 关 咖啡开关
# TODO:待定
LeftArmGripTurnOFFMachineSwitch:
  x_bias: -160
  y_bias: -78
  z_bias: 20  

# !!!!!以下为右臂

# 右臂抓零食
RightArmGripSnack:
  x_bias: -90
  y_bias: 78
  z_bias: 0

# 右臂松零食
# 相对于抓容器的位置
RightArmLossenSnack:
  x_bias: 50
  y_bias: 50
  z_bias: 20  # 380

# 右臂抓容器
RightArmGripContainer:
  x_bias : -60
  y_bias : 28
  z_const: 360


# 右臂抓杯子
RightArmGripCup:
  x_bias : -90
  y_bias : 78
  z_const: 220

# 右臂杯子倒水
RightArmWaterCup:
  x_bias : -195
  y_bias : 98
  z_const: 230