# 后退距离 [mm], 角度 [°] , 时间 [s]
SnackDeckMoveBack:
  x    : -2
  yaw  : -80
  time : 4

DrinkDeckMoveBack:
  x  : -50
  yaw: -90
  time : 4

LeftDeckMoveBack:
  x  : -50
  yaw: 90
  time : 3

RightDeckMoveBack:
  x  : -50
  yaw: -90
  time : 3

# 前进距离 [mm]
SnackDeckMoveforward:
  # x  : 25
  x  : 25
  yaw: 0
  time : 2.5

DrinkDeckMoveforward:
  x  : 15
  yaw: 0
  time : 2

LeftDeckMoveforward:
  x  : 20
  yaw: 0
  time : 2

RightDeckMoveforward:
  x  : 20
  yaw: 0
  time : 2