# 后退距离 [cm], 角度 [°] , 时间 [s]

SnackDeckFirstMoveBack:
  x    : -35
  yaw  : 0
  time : 3

SnackDeckMoveBack:
  x    : 15
  yaw  : -90
  time : 5

DrinkDeckMoveBack:
  x  : -70
  yaw: -180
  time : 6

LeftDeckMoveBack:
  x  : -50
  yaw: 90
  time : 4

RightDeckMoveBack:
  x  : -50
  yaw: -90
  time : 4

LeftDeckSecondMoveBack:
  x  : -20
  yaw: 0
  time : 2

RightDeckSecondMoveBack:
  x  : -20
  yaw: 0
  time : 2

# 前进距离 [cm]
SnackDeckMoveforward:
  x  : 25
  yaw: 0
  time : 2.5

DrinkDeckMoveforward:
  x  : 15
  yaw: 0
  time : 2

LeftDeckMoveforward:
  x  : 22
  yaw: 0
  time : 2

RightDeckMoveforward:
  x  : 22
  yaw: 0
  time : 2