# 后退距离 [mm]
SnackDeckMoveBack:
  x: -60
  y: 0

DrinkDeckMoveBack:
  x: -60
  y: +20

LeftDeckMoveBack:
  x: -30
  y: -20

RightDeckMoveBack:
  x: -30
  y: 20

# 前进距离 [mm]
SnackDeckMoveforward:
  x: 20
  y: 0

DrinkDeckMoveforward:
  x: 20
  y: 0

LeftDeckMoveforward:
  x: 30
  y: 0

RightDeckMoveforward:
  x: 30
  y: 0