# 后退距离 [mm], 角度 [°] , 时间 [s]
SnackDeckMoveBack:
  x    : -10
  yaw  : -50
  time : 4

DrinkDeckMoveBack:
  x  : -60
  yaw: -90
  time : 4

LeftDeckMoveBack:
  x  : -50
  yaw: 90
  time : 3

RightDeckMoveBack:
  x  : -50
  yaw: -90
  time : 3

# 前进距离 [mm]
SnackDeckMoveforward:
  x  : 25
  yaw: 0
  time : 2

DrinkDeckMoveforward:
  x  : 0.2
  yaw: 0
  time : 0.2

LeftDeckMoveforward:
  x  : 20
  yaw: 0
  time : 2

RightDeckMoveforward:
  x  : 20
  yaw: 0
  time : 2