# 后退距离 [cm], 角度 [°] , 时间 [s]

SnackDeckFirstMoveBack:
  x    : -10
  # x    : -8
  # yaw  : 70
  yaw  : 0
  time : 5

SnackDeckMoveBack:
  # x    : -45
  # x    : -8
  x    : 0
  yaw  : -70
  time : 5


DrinkDeckMoveBack:
  x  : -70
  yaw: -180
  time : 6

LeftDeckMoveBack:
  x  : -70
  yaw: 90
  time : 4

RightDeckMoveBack:
  x  : -70
  yaw: -90
  time : 4

# 前进距离 [mm]
SnackDeckMoveforward:
  x  : 25
  yaw: 0
  time : 2.5

DrinkDeckMoveforward:
  x  : 15
  yaw: 0
  time : 2

LeftDeckMoveforward:
  x  : 20
  yaw: 0
  time : 2

RightDeckMoveforward:
  x  : 20
  yaw: 0
  time : 2