# 后退距离 [mm]
SnackDeckMoveBack:
  x: -20
  y: -20

DrinkDeckMoveBack:
  x: -60
  y: -90

LeftDeckMoveBack:
  x: -50
  y: 80

RightDeckMoveBack:
  x: -60
  y: -80

# 前进距离 [mm]
SnackDeckMoveforward:
  x: 25
  y: 0

DrinkDeckMoveforward:
  x: 20
  y: 0

LeftDeckMoveforward:
  x: 30
  y: 0

RightDeckMoveforward:
  x: 30
  y: 0