# 后退距离 [cm], 角度 [°] , 时间 [s]

SnackDeckFirstMoveBack:
  x    : -25
  # x    : -8
  # yaw  : 70
  yaw  : 0
  time : 2

SnackDeckMoveBack:
  # x    : -45
  # x    : -8
  x    : 15
  yaw  : -90
  time : 5

DrinkDeckMoveBack:
  x  : -70
  yaw: -180
  time : 6

LeftDeckMoveBack:
  x  : -50
  yaw: 90
  time : 5

RightDeckMoveBack:
  x  : -50
  yaw: -90
  time : 5

LeftDeckSecondMoveBack:
  x  : -20
  yaw: 0
  time : 2

RightDeckSecondMoveBack:
  x  : -20
  yaw: 0
  time : 2

# 前进距离 [mm]
SnackDeckMoveforward:
  x  : 25
  yaw: 0
  time : 2.5

DrinkDeckMoveforward:
  x  : 15
  yaw: 0
  time : 2

LeftDeckMoveforward:
  x  : 20
  yaw: 0
  time : 2

RightDeckMoveforward:
  x  : 20
  yaw: 0
  time : 2