# 初始位姿
InitialPose:
  position_x: 0
  position_y: 0
  position_z: 0
  orientation_x: 0
  orientation_y: 0
  orientation_z: 0
  orientation_w: 1

# 零食台位姿
SnackDesk:
  position_x: 0.4800
  position_y: -2.4000
  position_z: 0
  orientation_x: 0
  orientation_y: 0
  orientation_z: 1
  orientation_w: 0
  
# 饮料台位姿
DrinkDesk:
  position_x: 0.53
  # position_y: -2.4666
  position_y: -2.26
  position_z: 0
  orientation_x: 0
  orientation_y: 0
  orientation_z: -0.684871
  orientation_w: 0.7028665


# 右服务台位姿
RightServiceDesk:
  # position_x: 2.257701
  position_x: 2.0
  position_y: -0.629783
  position_z: 0
  orientation_x: 0
  orientation_y: 0
  orientation_z: 0
  orientation_w: 1


# 左服务台位姿
LeftServiceDesk:
  # position_x:  2.3
  position_x:  2.0
  position_y: -2.05
  position_z: 0
  orientation_x: 0
  orientation_y: 0
  orientation_z: 0
  orientation_w: 1
