# 初始位姿
InitialPose:
  position_x: 0
  position_y: 0
  position_z: 0
  orientation_x: 0
  orientation_y: 0
  orientation_z: 0
  orientation_w: 1
  yaw: 3.14 


# 零食台位姿
SnackDesk:
  position_x: 0.967735
  position_y: -2.10476
  position_z: 0
  orientation_x: 0
  orientation_y: 0
  orientation_z: -0.724922
  orientation_w: 0.6888829
  yaw: 3.14 
  

# 饮料台位姿
DrinkDesk:
  position_x: 0.447
  position_y: -1.96947
  position_z: 0
  orientation_x: 0
  orientation_y: 0
  orientation_z: -0.710
  orientation_w: 0.703
  yaw: 3.14 

# 右服务台位姿
RightServiceDesk:
  position_x: 2.57372
  position_y: 2.23066
  position_z: 0
  orientation_x: 0
  orientation_y: 0
  orientation_z: 0.728588
  orientation_w: 0.684945
  yaw: 3.14 

# 左服务台位姿
LeftServiceDesk:
  position_x: 1.41546
  position_y: 2.3202
  position_z: 0
  orientation_x: 0
  orientation_y: 0
  orientation_z: 0.680037
  orientation_w: 0.733173
  yaw: 3.14
