# 初始位姿
InitialPose:
  position_x: 0
  position_y: 0
  position_z: 0
  yaw: 0

# 零食台位姿
SnackDesk:
  position_x: 0.42
  position_y: -2.35
  # position_y: -2.25
  position_z: 0
  yaw: -3.0
  
# 饮料台位姿
DrinkDesk:
  position_x: 0.58
  position_y: -2.35
  position_z: -0
  yaw: -1.52


# 右服务台位姿
RightServiceDesk:
  position_x: 1.92
  position_y: -0.55
  position_z: 0
  yaw: 0


# 左服务台位姿
LeftServiceDesk:
  position_x: 1.97
  position_y: -2.00
  position_z: 0
  yaw: 0
