TrajectoryPlannerROS:
# Robot Configuration Parameters
  max_vel_x: 1.5 # X 方向最大速度
  min_vel_x: 0.1 # X 方向最小速度
  max_vel_y: 0   # Y 方向最大速度
  min_vel_y: 0   # Y 方向最小速度
  max_vel_trans: 1.5 # 最大平移速度
  min_vel_trans: 0.1 # 最大平移速度
  trans_stopped_vel: 0.1 # 停止速度
  acc_lim_trans: 1.0 # 平移加速度限制
  acc_lim_x: 1.0 # X 加速限制
  acc_lim_y: 0.0 # Y 加速限制

  max_vel_theta:  1.0    # 最大旋转速度
  min_vel_theta: -0.01   # 当平移速度为0时，最小旋转速度
  theta_stopped_vel: 0.1 # 停止旋转速度
  acc_lim_theta: 6       # 角速度加速限制
  
  # Goal Tolerance Parameters，目标公差
  xy_goal_tolerance: 0.05          # 位置公差
  yaw_goal_tolerance: 0.05         # 角度公差
  latch_xy_goal_tolerance: false   # 达到目标容差范围后, 停止移动, 只旋转调整航向

# Differential-drive robot configuration
# 是否是全向移动机器人
  holonomic_robot: false

# Forward Simulation Parameters，前进模拟参数
  sim_time: 0.8             # 模拟时间
  vx_samples: 18            # X 方向速度采样点
  vy_samples: 1             # Y 方向速度采样点
  vtheta_samples: 20        # 旋转速度采样点
  sim_granularity: 0.05


# Trajectory scoring parameters 轨迹评分参数
path_distance_bias: 32.0       # 靠近全局路径的权重，默认值 32.0
goal_distance_bias: 24.0       # 接近导航目标点的权重，默认值 24.0
occdist_scale: 0.01            # 控制器避障的权重，默认值 0.01
forward_point_distance: 0.325  # 从机器人到评分点的位置，默认值 0.325
stop_time_buffer: 0.2          # 在碰撞前机器人必须停止的时间长度，留出缓冲空间，默认值 0.2
scaling_speed: 0.25            # 缩放机器人速度的绝对值，默认值 0.25
max_scaling_factor: 0.2        # 机器人足迹在高速时能缩放的最大系数，默认值 0.2

#防振动参数
oscillation_reset_dist: 1.05   # 重置振动标志前需要行进的距离，默认值0.05 

#辅助调试选项
publish_traj_pc: true          # 是否在RViz 里发布轨迹
publish_cost_grid_pc: true     # 是否在RViz 里发布代价网格
global_frame_id: odom          # 基础坐标系 